version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: my-mysql8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Uncomment if you have an init script

volumes:
  mysql_data:
