INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Afghanistan', '93', 'AF');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Albania', '355', 'AL');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Algeria', '213', 'DZ');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Andorra', '376', 'AD');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Angola', '244', 'AO');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Antigua and Barbuda', '1-268', 'AG');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Argentina', '54', 'AR');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Armenia', '374', 'AM');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Australia', '61', 'AU');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Austria', '43', 'AT');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Azerbaijan', '994', 'AZ');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Bahamas', '1-242', 'BS');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Bahrain', '973', 'BH');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Bangladesh', '880', 'BD');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Barbados', '1-246', 'BB');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Belarus', '375', 'BY');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Belgium', '32', 'BE');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Belize', '501', 'BZ');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Benin', '229', 'BJ');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Bhutan', '975', 'BT');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Bolivia', '591', 'BO');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Bosnia and Herzegovina', '387', 'BA');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Botswana', '267', 'BW');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Brazil', '55', 'BR');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Brunei', '673', 'BN');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Bulgaria', '359', 'BG');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Burkina Faso', '226', 'BF');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Burundi', '257', 'BI');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Cabo Verde', '238', 'CV');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Cambodia', '855', 'KH');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Cameroon', '237', 'CM');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Canada', '1', 'CA');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Central African Republic', '236', 'CF');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Chad', '235', 'TD');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Chile', '56', 'CL');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('China', '86', 'CN');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Colombia', '57', 'CO');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Comoros', '269', 'KM');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Congo (Congo-Brazzaville)', '242', 'CG');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Costa Rica', '506', 'CR');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Croatia', '385', 'HR');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Cuba', '53', 'CU');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Cyprus', '357', 'CY');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Czechia (Czech Republic)', '420', 'CZ');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Denmark', '45', 'DK');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Djibouti', '253', 'DJ');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Dominica', '1-767', 'DM');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Dominican Republic', '1-809, 1-829, 1-849', 'DO');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Ecuador', '593', 'EC');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Egypt', '20', 'EG');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('El Salvador', '503', 'SV');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Equatorial Guinea', '240', 'GQ');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Eritrea', '291', 'ER');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Estonia', '372', 'EE');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Eswatini (fmr. "Swaziland")', '268', 'SZ');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Ethiopia', '251', 'ET');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Fiji', '679', 'FJ');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Finland', '358', 'FI');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('France', '33', 'FR');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Gabon', '241', 'GA');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Gambia', '220', 'GM');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Georgia', '995', 'GE');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Germany', '49', 'DE');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Ghana', '233', 'GH');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Greece', '30', 'GR');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Grenada', '1-473', 'GD');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Guatemala', '502', 'GT');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Guinea', '224', 'GN');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Guinea-Bissau', '245', 'GW');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Guyana', '592', 'GY');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Haiti', '509', 'HT');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Holy See', '379', 'VA');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Honduras', '504', 'HN');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Hungary', '36', 'HU');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Iceland', '354', 'IS');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('India', '91', 'IN');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Indonesia', '62', 'ID');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Iran', '98', 'IR');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Iraq', '964', 'IQ');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Ireland', '353', 'IE');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Israel', '972', 'IL');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Italy', '39', 'IT');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Jamaica', '1-876', 'JM');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Japan', '81', 'JP');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Jordan', '962', 'JO');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Kazakhstan', '7', 'KZ');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Kenya', '254', 'KE');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Kiribati', '686', 'KI');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Korea, North', '850', 'KP');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Korea, South', '82', 'KR');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Kosovo', '383', 'XK');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Kuwait', '965', 'KW');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Kyrgyzstan', '996', 'KG');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Laos', '856', 'LA');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Latvia', '371', 'LV');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Lebanon', '961', 'LB');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Lesotho', '266', 'LS');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Liberia', '231', 'LR');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Libya', '218', 'LY');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Liechtenstein', '423', 'LI');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Lithuania', '370', 'LT');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Luxembourg', '352', 'LU');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Madagascar', '261', 'MG');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Malawi', '265', 'MW');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Malaysia', '60', 'MY');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Maldives', '960', 'MV');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Mali', '223', 'ML');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Malta', '356', 'MT');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Marshall Islands', '692', 'MH');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Mauritania', '222', 'MR');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Mauritius', '230', 'MU');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Mexico', '52', 'MX');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Micronesia', '691', 'FM');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Moldova', '373', 'MD');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Monaco', '377', 'MC');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Mongolia', '976', 'MN');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Montenegro', '382', 'ME');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Morocco', '212', 'MA');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Mozambique', '258', 'MZ');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Myanmar (formerly Burma)', '95', 'MM');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Namibia', '264', 'NA');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Nauru', '674', 'NR');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Nepal', '977', 'NP');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Netherlands', '31', 'NL');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('New Zealand', '64', 'NZ');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Nicaragua', '505', 'NI');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Niger', '227', 'NE');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Nigeria', '234', 'NG');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('North Macedonia (formerly Macedonia)', '389', 'MK');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Norway', '47', 'NO');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Oman', '968', 'OM');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Pakistan', '92', 'PK');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Palau', '680', 'PW');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Palestine State', '970', 'PS');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Panama', '507', 'PA');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Papua New Guinea', '675', 'PG');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Paraguay', '595', 'PY');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Peru', '51', 'PE');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Philippines', '63', 'PH');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Poland', '48', 'PL');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Portugal', '351', 'PT');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Qatar', '974', 'QA');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Romania', '40', 'RO');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Russia', '7', 'RU');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Rwanda', '250', 'RW');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Saint Kitts and Nevis', '1-869', 'KN');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Saint Lucia', '1-758', 'LC');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Saint Vincent and the Grenadines', '1-784', 'VC');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Samoa', '685', 'WS');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('San Marino', '378', 'SM');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Sao Tome and Principe', '239', 'ST');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Saudi Arabia', '966', 'SA');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Senegal', '221', 'SN');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Serbia', '381', 'RS');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Seychelles', '248', 'SC');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Sierra Leone', '232', 'SL');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Singapore', '65', 'SG');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Slovakia', '421', 'SK');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Slovenia', '386', 'SI');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Solomon Islands', '677', 'SB');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Somalia', '252', 'SO');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('South Africa', '27', 'ZA');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('South Sudan', '211', 'SS');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Spain', '34', 'ES');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Sri Lanka', '94', 'LK');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Sudan', '249', 'SD');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Suriname', '597', 'SR');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Sweden', '46', 'SE');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Switzerland', '41', 'CH');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Syria', '963', 'SY');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Taiwan', '886', 'TW');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Tajikistan', '992', 'TJ');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Tanzania', '255', 'TZ');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Thailand', '66', 'TH');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Timor-Leste', '670', 'TL');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Togo', '228', 'TG');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Tonga', '676', 'TO');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Trinidad and Tobago', '1-868', 'TT');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Tunisia', '216', 'TN');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Turkey', '90', 'TR');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Turkmenistan', '993', 'TM');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Tuvalu', '688', 'TV');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Uganda', '256', 'UG');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Ukraine', '380', 'UA');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('United Arab Emirates', '971', 'AE');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('United Kingdom', '44', 'GB');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('United States of America', '1', 'US');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Uruguay', '598', 'UY');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Uzbekistan', '998', 'UZ');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Vanuatu', '678', 'VU');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Venezuela', '58', 'VE');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Vietnam', '84', 'VN');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Yemen', '967', 'YE');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Zambia', '260', 'ZM');
INSERT INTO entrelazos.country (name, code, alpha_code) VALUES('Zimbabwe', '263', 'ZW');