name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Debian SSH machine
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_HOST_USERNAME }}
          key: ${{ secrets.SSH_HOST_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_HOST_PASSPHRASE }}
          script: |
            eval "$(ssh-agent -s)"
            echo "Adding SSH key"
            echo "${{ secrets.SSH_PRIVATE_KEY }}" | ssh-add -
            cd nest-entrelazos
            git pull origin master
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            npm install
            npm run build
            pm2 restart dist/src/main.js
        env:
          NODE_ENV: production
          DB_CONNECTION: mysql
          PORT: 3000
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_DATABASE: entrelazos
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

